### ISSUE TITLE
Support dot notation

### ISSUE THREAD

**Issue by theonlyelf** [feathersjs/feathers-authentication-local#7]
This is just a simple feature request, but it'd be great if `usernameField` and `passwordField` both supported dot notation.

**Comment by lionelrudaz** [comment]
I confirm, this would be awesome. I talked about that in the #help channel on Slack. If you don't use a flat structure in your user service response (for example with JSON API standard), you simply can't do anything. I'm currently commenting the line 52 of verifier.js with my own path, but that's not good.

Let me know if we can help.

Cheers,

Lionel

**Comment by daffl** [comment]
The workaround right now is to [implement your own verifier methods](https://github.com/feathersjs/feathers-authentication-local#verifier).

It's a good feature though and definitely worth adding. We'll happily accept a pull request with tests that changes https://github.com/feathersjs/feathers-authentication-local/blob/master/src/verifier.js#L23 to use [lodash .get](https://lodash.com/docs/4.17.4#get):

```js
const hash = get(entity, this.options.passwordField);
```

**Comment by mz103** [comment]
@daffl I'd love to add it, though I'm not really well versed in writing tests - do you have any resources/articles you found helpful that you could link me to?

**Comment by daffl** [comment]
You can probably copy the test from https://github.com/feathersjs/feathers-authentication-local/blob/master/test/verifier.test.js#L92-L98 to the next line and change it to this

```js
describe('password comparison succeeds', () => {
  it('allows dot notation for password field', () => {
    const oldPasswordField = verifier.options.passwordField;

    verifier.options.passwordField = 'nested.password';

    return verifier._comparePassword({
      nested: user
    }, 'admin').then(result => {
      expect(result).to.deep.equal(user);
      verifier.options.passwordField = oldPaswordField;
    });
  });
});
```

**Comment by theonlyelf** [comment]
Just solved this via #8

**Comment by lionelrudaz** [comment]
Thanks @daffl and @theonlyelf, looking forward to use it!

**Comment by theonlyelf** [comment]
We've decided to remove the `usernameField` dot notation implementation. It wasn't exactly functional, and with so many different database drivers, wouldn't have worked across too many.

For now, it's a better idea to write your own custom verifier function that queries documents with dot notation.

**Comment by lionelrudaz** [comment]
Awesome, thanks. I finally ended up doing my own Verifier for exactly this reason.

**Comment by elfey** [comment]
@lionelrudaz care to share? I haven't gotten the chance to hop in an write my own yet.

**Comment by lionelrudaz** [comment]
Sure, here it is: https://github.com/lionelrudaz/api.wellnow.ch/blob/master/src/verifier.js

I call it from the app: https://github.com/lionelrudaz/api.wellnow.ch/blob/master/src/app.js

Hope this helps.
